### ISSUE TITLE
Ability to download a variety of sizes [FEATURE]

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/facecreator#36]
**Is your feature request related to a problem? Please describe.**
Depending on where you'd like to use the image, you might want different dimensions. I'm specifically thinking of a smaller version for email signatures.

**Describe the solution you'd like**
Add a bootstrap button group that lets you choose between "SM" (80px), "MD" (140px), and "LG" (293 px - the current size).

**Describe how this would help the community as a whole**
It would create more flexibility in how people use the images, and would reduce unnecessarily large files when only a small size is needed.

**Comment by seanmetzgar** [comment]
Resolved in PR #38 :happy:
